# See README.md - docker-compose layout

version: "3.9"

services: 
  nginx:
    image: nginx:latest
    container_name: nginx_production
    command: # Substitute environment variables in our nginx config file.
      /bin/bash -c "envsubst < /chattr/nginx/chattr.template > /etc/nginx/conf.d/default.conf &&
       nginx -g 'daemon off;'"
    env_file: 
      - .env
    volumes:
      - static-files:${STATIC_FILES}
      - ./nginx:/chattr/nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    networks:
      - frontend
    depends_on:
      - daphne 

  daphne:
    container_name: daphne_production
    env_file: 
      - .env
    build: .
    command: bash -c "
        python manage.py migrate
        && python manage.py collectstatic --noinput
        && python manage.py createsuperuser --noinput
        && daphne -b 0.0.0.0 -p ${DAPHNE_PORT} --access-log - chattr.asgi:application"
    volumes:
      - static-files:${STATIC_FILES}
    ports:
      - ${DAPHNE_PORT}:${DAPHNE_PORT}
    networks:
      - frontend
      - backend
    depends_on: 
      - redis
      - postgres
  
  redis:
    image: redis
    container_name: redis_production
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - backend

  postgres:
    image: postgres
    container_name: postgres_production
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: 
      - .env
    volumes: 
      # The database volume (postgres-data) is automatically created inside '/var/lib/docker/volumes'.
      - postgres-data:/var/lib/postgresql/data # Link our volume with the database folder
    networks:
      - backend

volumes:
  postgres-data:
  static-files:

networks:
  frontend:
  backend:
