# TODO: Fix nginx not being able to connect with daphne 

# The app is composed of four services: nginx, daphne, redis and postgres:
#
# nginx works as a reverse proxy which serves static files and routes websocket traffic to daphne.
# static files are located in 'nginx/collected_static'
#
# Our app runs inside daphne, which handles websocket requests and communicates with the database.
# Websocker connections are set on port 8000
#
# redis is an in-memory data structure used as a database, cache, and message broker.
#
# Database environment variables (POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD) and static file location
# (STATIC_FILES) should be defined in 'variable.env'
# The database volume is automatically created in '/var/lib/docker/volumes'
#
# Services who do not need to know about each other are isolated through the use of two networks,
# 'frontend' (nginx - daphne), and 'backend' (daphne - redis - postgres)

version: "3.9"

services: 
  nginx:
    image: nginx:latest
    container_name: nginx_production
    command: >-
      /bin/bash -c "envsubst < /chattr/nginx/chattr.template > /etc/nginx/conf.d/default.conf &&
       nginx -g 'daemon off;'" # Substitute environment variables in our nginx config file
    env_file: 
      - .env
    volumes:
      - static-files:${STATIC_FILES}
      - ./nginx:/chattr/nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    networks:
      - frontend
    depends_on:
      - daphne 

  daphne:
    container_name: daphne_production
    env_file: 
      - .env
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p ${DAPHNE_PORT} --access-log - chattr.asgi:application"
    volumes:
      - static-files:${STATIC_FILES}
    ports:
      - ${DAPHNE_PORT}:${DAPHNE_PORT}
    networks:
      - frontend
      - backend
    depends_on: 
      - redis
      - postgres
  
  redis:
    image: redis
    container_name: redis_production
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - backend

  postgres:
    image: postgres
    container_name: postgres_production
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: 
      - .env
    volumes: 
      - postgres-data:/var/lib/postgresql/data # Link our volume with the database folder
    networks:
      - backend

volumes:
  postgres-data:
  static-files:

networks:
  frontend:
  backend: