name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Export Environment Variables
      run: export $(cat .env | xargs)
    - name: Run Redis
      run: docker run -p 6379:6379 -d redis:5
    - name: Run Tests
      run: |
        python manage.py test
        
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH Key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNWON_HOSTS}}
        SSH_KEY_PATH: ${{github.workspace}}/../private.key
        
    - name: Update Remote Server
      run: |
        ssh -i $SSH_KEY_PATH -p 222 dante@dantepc.ddns.net
        cd ~/code/chattr
        docker-compose down
        git fetch origin/master
        git reset --hard origin/master
        docker-compose up
