name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to personal server"
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          fingerprint: ${{secrets.SSH_FINGERPRINT}}
          script: |
            cd /home/dante/code/chattr
            docker-compose down
            git fetch
            git reset --hard origin/master
            docker-compose up --build
