name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to personal server"
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Deploy with SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh -p $SSH_PORT -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST 'cd /home/dante/code/chattr; docker-compose down; git fetch; git reset --hard origin/master; docker-compose up --build'
        shell: bash
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
