name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to personal server"
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: $SSH_HOST
          username: $SSH_USER
          port: $SSH_PORT
          fingerprint: $SSH_KNOWN_HOSTS
          key: $SSH_PRIVATE_KEY
          key_path: $SSH_KEY_PATH
          script: |
            cd /home/dante/code/chattr
            docker-compose down
            git fetch
            git reset --hard origin/master
            docker-compose up --build
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
